CREATE TABLE `cats` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`photoUrl` varchar(1024),
	`breed` varchar(255) DEFAULT 'Domestic Shorthair',
	`colorPattern` varchar(255),
	`dob` timestamp,
	`catSex` enum('female','male','unknown') NOT NULL DEFAULT 'unknown',
	`weight` varchar(50),
	`personalityTags` json,
	`bio` text,
	`adoptionFee` varchar(50) DEFAULT '$150.00',
	`isAltered` boolean NOT NULL DEFAULT false,
	`felvFivStatus` enum('negative','positive','unknown','not_tested') NOT NULL DEFAULT 'not_tested',
	`catStatus` enum('available','adopted','medical_hold','foster','trial') NOT NULL DEFAULT 'available',
	`rescueId` varchar(100),
	`shelterluvId` varchar(100),
	`microchipNumber` varchar(100),
	`arrivalDate` timestamp,
	`intakeType` varchar(100),
	`medicalNotes` text,
	`vaccinationsDue` json,
	`fleaTreatmentDue` timestamp,
	`adoptedDate` timestamp,
	`adoptedBy` varchar(255),
	`isFeatured` boolean NOT NULL DEFAULT false,
	`sortOrder` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cats_id` PRIMARY KEY(`id`)
);
